```{r}
library(Seurat)
library(celda)

#################################################################
# Module split
#################################################################
# FIXME: I need to filter the samples by those that are european ancestry
sce <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
sce <- as.SingleCellExperiment(sce, assay = "SCT")
#
useAssay <- "counts"
altExpName <- "featureSubset"
sce <- selectFeatures(sce, minCount = 3, minCell = 3, useAssay = useAssay, altExpName = altExpName)
nrow(altExp(sce, altExpName)) # 13302 genes remaining

moduleSplit <- recursiveSplitModule(sce, useAssay = useAssay, altExpName = altExpName, initialL = 10, maxL = 100, sampleLabel = sce$Sample_ID, verbose = T, zInit = as.numeric(factor(sce$seurat_clusters)))
saveRDS(moduleSplit, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/splitModule_astros.rds")
# saveRDS(moduleSplit45_245,file='~/SingleCellPr

pdf("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/perplexityPlots_splitModule.pdf", width = 15)
plotGridSearchPerplexity(moduleSplit, altExpName = altExpName)
plotRPC(moduleSplit, altExpName = altExpName)
dev.off()

#################################################################
# cell split
#################################################################
L <- 65
temp <- subsetCeldaList(moduleSplit, list(L = L))
cModules <- celdaModules(temp)
rm(moduleSplit)
rm(temp)
t1 <- Sys.time()
sce <- recursiveSplitCell(sce, useAssay = useAssay, altExpName = altExpName, initialK = 3, maxK = 25, sampleLabel = sce$Sample_ID, yInit = cModules)
gc()
myTime <- difftime(Sys.time(), t1)
library(qs)
qsave(sce, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)

pdf("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/perplexityPlots_clusters.pdf", width = 15)
plotGridSearchPerplexity(sce, altExpName = altExpName)
plotRPC(sce, altExpName = altExpName)
dev.off()

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
t1 <- Sys.time()
k8 <- celdaUmap(k8, useAssay = useAssay, altExpName = altExpName)
reducedDimNames(altExp(k8, altExpName))
pdf(sprintf("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/umap_astro_L65_K%s.pdf", K))
plotDimReduceCluster(k8, reducedDimName = "celda_UMAP", labelClusters = TRUE)
dev.off()
cat(difftime(Sys.time(), t1))

table(k8$seurat_clusters, celdaClusters(k8))
table(k8$Sample_ID, celdaClusters(k8))

pdf(sprintf("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/heatmap_modulesToClusters_K%s.pdf", K), height = 12)
celdaProbabilityMap(k8, useAssay = useAssay, altExpName = altExpName)
dev.off()
```
  
```{r, run sex interaction model for all module cluster pairs}
############################################################
# run sex interaction model for all modules
############################################################
library(qs)
library(lme4)
library(lmerTest)

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
K <- 8
L <- 65
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)

mdata <- readRDS("~/SingleCellProjects/dataObjects/allCellTypes_garnettCleaned_finalObj_294114nuclei_metaData.rds")
mdata <- mdata[colnames(k8), ]
fm <- factorizeMatrix(k8)
allModDF <- data.frame(t(fm$proportions$cell), Sex = mdata$Gender, celdaCluster = paste0("K", celdaClusters(k8)), cellType = mdata$cellType, cellState = mdata$cellState, Status = mdata$Status, Sample = mdata$Sample_ID)
allModFilt <- allModDF
allModFilt$Status <- factor(allModFilt$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))

# determine the module-cluster pairs to test
pairs <- apply(fm$proportions$cellPopulation, 1, function(r) {
  z <- kmeans(r, centers = 2)
  return(names(z$cluster)[which(z$cluster == names(table(z$cluster))[which(table(z$cluster) == min(table(z$cluster)))])]) # get the cluster names of the clusters which have high expression of the module
})
# clustToCellType = c('Astro','Astro','Astro','Astro','Oligo','Oligo','Oligo','Oligo','Endo','Micro')
# names(clustToCellType) = paste0('K',1:8)
clusts <- pairs # lapply(pairs,function(p) unique(clustToCellType[p]))

# the following code is to run the sex*AD model for each module
t1 <- Sys.time()
# cstates = names(table(allModFilt$cellState))
allModuleResults <- lapply(seq_len(nrow(fm$proportions$cellPopulation)), function(idx) {
  mod <- paste0("L", idx)
  cs <- clusts[[idx]] # names(table(allModFilt$cellState))[grep(paste(clusts[[idx]],collapse = '|'),cstates)]
  results <- lapply(cs, function(cstate) {
    re_ln2 <- NA
    try({
      re_ln2 <- lmer(paste0(mod, " ~ Sex + Status +  Sex*Status + (1|Sample)"), data = allModFilt[allModFilt$celdaCluster == cstate, ], REML = TRUE)
    }) # nebula(m$DAM_up1,m@meta.data$Sample_ID,pred=pred,method='LN',model='gaussain')#'NBLMM')
    return(summary(re_ln2))
  })
  names(results) <- cs
  return(results)
})
cat(difftime(Sys.time(), t1))
names(allModuleResults) <- paste0("L", seq_len(nrow(fm$proportions$cellPopulation)))

# the following code prints the results that are less than 0.01
sAD_pvals <- c()
tmp <- lapply(names(allModuleResults), function(mod) {
  lapply(names(allModuleResults[[mod]]), function(res) {
    c <- NA
    try({
      c <- allModuleResults[[mod]][[res]]$coefficients
    })
    if (!sum(is.na(c))) {
      if ("Sex2:StatusNeuro_AD" %in% rownames(c)) {
        sAD_pvals <<- c(sAD_pvals, c["Sex2:StatusNeuro_AD", "Pr(>|t|)"])
        names(sAD_pvals)[length(sAD_pvals)] <<- mod
        if (sum(c["Sex2:StatusNeuro_AD", "Pr(>|t|)"] < 0.05) > 0) {
          print(sprintf("%s : %s", mod, res))
          # print(mod)
          print(c[c("Sex2", "Sex2:StatusNeuro_AD"), ])
        }
      }
    }
  })
})
# [1] "L3 : K6"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.002292972 0.001089180 53.95973  2.105227 0.03994224
# Sex2:StatusNeuro_AD -0.002650842 0.001228352 54.44279 -2.158048 0.03535213
# [1] "L17 : K6"
#                        Estimate  Std. Error       df   t value    Pr(>|t|)
# Sex2                 0.003387112 0.001604177 51.54808  2.111434 0.039602671
# Sex2:StatusNeuro_AD -0.004944597 0.001807805 52.01108 -2.735138 0.008507259
# [1] "L17 : K8"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.001991930 0.001108780 39.13842  1.796506 0.08013549
# Sex2:StatusNeuro_AD -0.002834512 0.001279667 38.92864 -2.215039 0.03267788
# [1] "L28 : K8"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.002646353 0.001846254 40.45212  1.433363 0.15943836
# Sex2:StatusNeuro_AD -0.004488354 0.002133226 40.27404 -2.104022 0.04166603
# [1] "L29 : K8"
#                       Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.01111246 0.005660785 40.70503  1.963059 0.05649726
# Sex2:StatusNeuro_AD -0.01401547 0.006541727 40.53433 -2.142473 0.03821207
# [1] "L38 : K5"
#                        Estimate  Std. Error       df   t value  Pr(>|t|)
# Sex2                 0.004268331 0.003262932 37.92255  1.308128 0.1987040
# Sex2:StatusNeuro_AD -0.008254513 0.003636325 38.18058 -2.270015 0.0289354
# [1] "L43 : K8"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.002804168 0.002414806 41.40949  1.161240 0.25219474
# Sex2:StatusNeuro_AD -0.006462567 0.002789287 41.21300 -2.316924 0.02555351
# [1] "L49 : K2"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                -0.002670817 0.002165159 45.55841 -1.233543 0.22369953
# Sex2:StatusNeuro_AD  0.005258111 0.002361691 43.46578  2.226418 0.03121877
# [1] "L55 : K2"
#                        Estimate  Std. Error       df   t value    Pr(>|t|)
# Sex2                -0.003379798 0.001719706 63.46125 -1.965335 0.053755433
# Sex2:StatusNeuro_AD  0.005463323 0.001858637 57.42211  2.939424 0.004730084
# [1] "L65 : K1"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.004142825 0.001827472 46.09835  2.266970 0.02812722
# Sex2:StatusNeuro_AD -0.004386848 0.002021856 44.15016 -2.169713 0.035452330

sAD_BH <- p.adjust(sAD_pvals, "BH") # 1484 tests
names(sAD_BH) <- names(sAD_pvals)
## [1] "L55 : K2"
## Estimate  Std. Error       df   t value    Pr(>|t|)
## Sex2                -0.003370788 0.001762226 58.31027 -1.912801 0.060688760
## Sex2:StatusNeuro_AD  0.005456711 0.001905375 52.89134  2.863851 0.005988345
## L17 : K6
```
```{r, run sex interaction models on the top genes for K6:L17 and K2:L55}
#################################################################
# run sex interaction models on the top genes for L17
#################################################################
library(qs)
library(celda)

CLUSTER_HIT <- c("K6", "K2")
MOD_HITS <- c("L17", "L55")

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
L <- 65
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
fm <- factorizeMatrix(k8)

modListFull <- lapply(colnames(fm$posterior$module), function(mod) {
  return(fm$posterior$module[, mod])
})
modListFull <- lapply(modListFull, function(mod) {
  return(mod[order(mod, decreasing = T)])
})
names(modListFull) <- colnames(fm$posterior$module)
mod80Full <- lapply(modListFull, function(mod) { # using this filtering method: on average 23% of the genes for each module make up 80% of the overall signal
  ind <- 1
  while (sum(mod[1:ind]) < 0.8) ind <- ind + 1
  return(mod[1:ind])
})
names(mod80Full) <- colnames(fm$posterior$module)
genes <- lapply(MOD_HITS, function(mod) {
  return(names(mod80Full[[mod]]))
})
names(genes) <- CLUSTER_HIT
rm(modListFull)
rm(mod80Full)

library(nebula)
library(Seurat)
library(qs)

pvalue.extreme <- function(z) {
  log.pvalue <- log(2) + pnorm(abs(z), lower.tail = FALSE, log.p = TRUE)
  log10.pvalue <- log.pvalue / log(10) ## from natural log to log10
  mantissa <- 10^(log10.pvalue %% 1)
  exponent <- log10.pvalue %/% 1
  ## or return(c(mantissa,exponent))
  # return(sprintf("p value is %1.2f times 10^(%d)",mantissa,exponent))
  return(sprintf("%1.2fE%d", mantissa, exponent))
}

# subclust1 = '6'#K6
date <- format(Sys.Date(), format = "%m.%d.%y")

m <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
m$celdaClusters <- paste0("K", celdaClusters(k8))
rm(k8)
m <- subset(m, subset = Sample_ID %in% names(table(m@meta.data$Sample_ID)[table(m@meta.data$Sample_ID) > 60])) # 60]))
m$Clusters <- Idents(m)
# m = subset(m,subset=celdaClusters == subclust1)
# m = subset(m,subset=Status %in% c('Neuro_CO','Neuro_AD'))#,'Neuro_ADAD') )

genes <- lapply(genes, function(g) {
  return(g[g %in% rownames(m)])
})

m$Sex <- as.factor(m$Gender)
m$AOD <- scale(as.numeric(m$AOD))
m$PMI <- scale(as.numeric(m$PMI))
m$Status <- factor(m$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))

allDE <- NULL
msub <- NULL
tmp <- lapply(CLUSTER_HIT, function(K) {
  msub <<- subset(m, subset = celdaClusters == K)
  pred <- model.matrix(~ Sex + Status + Sex * Status, data = msub@meta.data) # adding AOD dropped the lambda to 1.15 instead of 1.28
  re_ln2 <- nebula(GetAssayData(msub, slot = "counts")[genes[[K]], ], msub@meta.data$Sample_ID, pred = pred, method = "LN", model = "NBLMM")
  tmp2 <- data.frame("logFC_Sex.StatusNeuro_AD" = re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"])
  tmp2$z.score <- re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"] / re_ln2$summary[, "se_Sex2:StatusNeuro_AD"]
  tmp2$p.value <- pvalue.extreme(tmp2$z.score)
  tmp2$BH <- p.adjust(re_ln2$summary[, "p_Sex2:StatusNeuro_AD"], "BH")
  merged2 <- merge(tmp2, re_ln2$summary, by.x = "logFC_Sex.StatusNeuro_AD", by.y = "logFC_Sex2:StatusNeuro_AD")
  rownames(merged2) <- merged2$gene
  merged2 <- merged2[order(abs(merged2$z.score), decreasing = T), ]
  allDE <<- rbind(allDE, merged2)
})
allDE$BHcombined <- p.adjust(allDE$p.value, "BH")
allDE <- allDE[order(abs(allDE$z.score), decreasing = T), ]
write.table(t(allDE[seq(sum(as.numeric(allDE$p.value) < 0.05)), c("logFC_Sex2", "logFC_StatusNeuro_AD", "logFC_Sex.StatusNeuro_AD", "p_Sex2", "p_StatusNeuro_AD", "p.value", "BH", "BHcombined")]), file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/sex_AD_interaction_genes_by_cluster.csv", sep = ",", quote = F, row.names = T, col.names = T)

# plot significant genes
library(ggplot2)
library(cowplot)
###########################################################################################################################
# only genes from the K6:L17 analysis are significant
sigGenes <- c("CD38", "ARMH1", "FAM189A2") # rownames(allDE)[allDE$BHcombined < 0.05]
m <- subset(m, subset = celdaClusters == "K6")
df <- data.frame(t(GetAssayData(m, slot = "counts")[sigGenes, ]), Sex = as.character(m$Sex), Status = unlist(lapply(m$Status, function(x) strsplit(as.character(x), "_")[[1]][2])))
df$Status[df$Status == "AD"] <- "sAD"
df$Sex[df$Sex == 1] <- "Male"
df$Sex[df$Sex == 2] <- "Female"
df$Status_Sex <- paste(df$Status, df$Sex, sep = "-")
df$Status_Sex <- factor(df$Status_Sex, levels = c("CO-Female", "sAD-Female", "CO-Male", "sAD-Male"))
df <- na.omit(df)
colnames(df)[which(colnames(df) == "FAM189A2")] <- sigGenes[which(sigGenes == "FAM189A2")] <- "ENTREP1"
plts <- lapply(sigGenes, function(gene) {
  p <- ggplot(na.omit(df), aes(x = Status_Sex, y = log(UQ(as.name(gene)) + 1), fill = Sex)) +
    geom_jitter(size = 0.5) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
    stat_summary(fun = "mean", geom = "crossbar", width = 0.75, color = "red") +
    ggtitle(gene) +
    theme_minimal() +
    xlab("Status-Sex") +
    theme(axis.text = element_text(color = "black"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  return(p)
})
q <- plot_grid(plotlist = plts, ncol = 2, nrow = ceiling(length(sigGenes) / 2))
ggsave(q, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/astro_sex_AD_interaction_gene_hits_by_cluster.pdf", w = 8, h = 4.5 * ceiling(length(sigGenes) / 2))
```
```{r run sex interaction model for all astrocytes}
############################################################
# run sex interaction model for all astrocytes
############################################################
library(qs)
library(lme4)
library(lmerTest)
library(celda)

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8) # ANCHOR don't lose this file name
K <- 8
L <- 65
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)

mdata <- readRDS("~/SingleCellProjects/dataObjects/allCellTypes_garnettCleaned_finalObj_294114nuclei_metaData.rds")
mdata <- mdata[colnames(k8), ]
fm <- factorizeMatrix(k8)
allModDF <- data.frame(t(fm$proportions$cell), Sex = mdata$Gender, celdaCluster = paste0("K", celdaClusters(k8)), cellType = mdata$cellType, cellState = mdata$cellState, Status = mdata$Status, Sample = mdata$Sample_ID)
# allModFilt = allModDF[allModDF$Status %in% c('Neuro_CO','Neuro_AD','Neuro_ADAD'),]
allModFilt <- allModDF
allModFilt$Status <- factor(allModFilt$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))

# the following code is to run the sex*AD model for each module in all astrocytes
t1 <- Sys.time()
allModuleResults <- lapply(seq_len(nrow(fm$proportions$cellPopulation)), function(idx) {
  mod <- paste0("L", idx)
  re_ln2 <- NA
  try({
    re_ln2 <- lmer(paste0(mod, " ~ Sex + Status + celdaCluster + Sex*Status + (1|Sample)"), data = allModFilt, REML = TRUE)
  }) # nebula(m$DAM_up1,m@meta.data$Sample_ID,pred=pred,method='LN',model='gaussain')#'NBLMM')
  return(summary(re_ln2))
})
cat(difftime(Sys.time(), t1))
names(allModuleResults) <- paste0("L", seq_len(nrow(fm$proportions$cellPopulation)))

# the following code prints the results that are less than 0.05
sAD_pvals <- c()
tmp <- lapply(names(allModuleResults), function(mod) {
  c <- NA
  try({
    c <- allModuleResults[[mod]]$coefficients
  })
  if (!sum(is.na(c))) {
    # if (nrow(c)==6){
    # if (nrow(c) == 10) {
    sAD_pvals <<- c(sAD_pvals, c["Sex2:StatusNeuro_AD", "Pr(>|t|)"])
    names(sAD_pvals)[length(sAD_pvals)] <<- mod
    if (sum(c["Sex2:StatusNeuro_AD", "Pr(>|t|)"] < 0.05) > 0) {
      # print(sprintf('%s : %s',mod,res))
      print(mod)
      print(c[c("Sex2", "Sex2:StatusNeuro_AD"), ])
    }
    # }
  }
})
## don't use BH correction because there are too many tests
# sAD_BH <- p.adjust(sAD_pvals, "BH") # 1484 tests
# names(sAD_BH) <- names(sAD_pvals)
# sAD_BH = sAD_BH[order(sAD_BH, decreasing = FALSE)]

# [1] "L3"
#                        Estimate   Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.001225916 0.0005391562 55.64522  2.273768 0.02685879
# Sex2:StatusNeuro_AD -0.001244991 0.0006059600 55.85742 -2.054576 0.04460951

# [1] "L17"
#                        Estimate  Std. Error       df   t value   Pr(>|t|)
# Sex2                 0.002718711 0.001246999 56.42236  2.180202 0.03342937
# Sex2:StatusNeuro_AD -0.003599103 0.001400747 56.53215 -2.569417 0.01285069

# [1] "L55"
#                        Estimate   Std. Error       df   t value   Pr(>|t|)
# Sex2                -0.001202368 0.0006565699 56.71610 -1.831287 0.07231193
# Sex2:StatusNeuro_AD  0.001490784 0.0007382574 57.01119  2.019328 0.04816359
```
```{r violin plots of modules}
#################################################################
# violin plots of modules
#################################################################
fm <- factorizeMatrix(k8)
mods <- unlist(lapply(which(sAD_pvals < 0.05), function(idx) {
  return(strsplit(names(sAD_pvals)[idx], "_")[[1]][1])
}))
cStates <- unlist(lapply(which(sAD_pvals < 0.05), function(idx) {
  return(strsplit(names(sAD_pvals)[idx], "_")[[1]][2])
}))
apply(fm$posterior$module, 2, function(mod) {
  return(sum(mod >= 0.01))
})[mods] # how many genes contribute more than 1% to the total module score
apply(fm$posterior$module, 2, function(mod) {
  return(sum(mod[mod >= 0.01]))
})[mods] # using those genes what is their combined contribution

# violin plots of these hits
library(ggplot2)
library(cowplot)
plts <- lapply(1:length(mods), function(ind) {
  df <- data.frame(Module_Score = allModFilt[, mods[ind]], Status_Sex = paste(allModFilt$Status, allModFilt$Sex, sep = "_"), Sex = allModFilt$Sex, Status = allModFilt$Status, celdaCluster = allModFilt$celdaCluster, cellState = allModFilt$cellState, Sample = allModFilt$Sample)
  df <- df[df$celdaCluster == cStates, ]
  df$Status_Sex <- factor(df$Status_Sex, levels = c("Neuro_CO_1", "Neuro_AD_1", "Neuro_ADAD_1", "Neuro_CO_2", "Neuro_AD_2", "Neuro_ADAD_2"))
  p <- ggplot(df, aes(x = Status_Sex, y = Module_Score, fill = Sex)) +
    geom_jitter() +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.75) +
    stat_summary(fun = "mean", geom = "crossbar", width = 0.75, color = "red") +
    ggtitle(sprintf("%s : %s", mods[ind], cStates[ind]))
  return(p)
})
q <- plot_grid(plotlist = plts, ncol = 3, nrow = ceiling(length(mods) / 3))
ggsave(q, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celdaModule_sexInteraction_violinPlots.pdf", w = 21, h = 7 * ceiling(length(mods) / 3))

# get genes in module
# modList = lapply(unique(mods),function(mod) return(fm$posterior$module[,mod]))
# modList = lapply(modList,function(mod) return(mod[order(mod,decreasing = T)]))
# modFilt  = lapply(modList, function(mod) return(mod[mod >= 0.01]))
# names(modFilt) = unique(mods)
modListFull <- lapply(colnames(fm$posterior$module), function(mod) {
  return(fm$posterior$module[, mod])
})
modListFull <- lapply(modListFull, function(mod) {
  return(mod[order(mod, decreasing = T)])
})
names(modListFull) <- colnames(fm$posterior$module)
# saveRDS(modListFull,file='moduleGenes_allCellTypes.rds')
mod80Full <- lapply(modListFull, function(mod) { # using this filtering method: on average 23% of the genes for each module make up 80% of the overall signal
  ind <- 1
  while (sum(mod[1:ind]) < 0.8) ind <- ind + 1
  return(mod[1:ind])
})
names(mod80Full) <- colnames(fm$posterior$module)
unlist(lapply(mods, function(m) length(mod80Full[[m]]))) # genes that make up 80% of module signal
unlist(lapply(mods, function(m) length(mod80Full[[m]]))) / unlist(lapply(mods, function(m) length(modListFull[[m]][modListFull[[m]] != 0]))) # percentage of genes needed to make 80% of signal
```
```{r, check to see which modules are associated with AD status, APOE, or rs1582763}
#################################################################
# check to see if L17 is associated with AD status
#################################################################
library(qs)
library(lme4)
library(lmerTest)
library(celda)

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
K <- 8
L <- 65
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)

mdata <- readRDS("~/SingleCellProjects/dataObjects/allCellTypes_garnettCleaned_finalObj_294114nuclei_metaData.rds")
mdata <- mdata[colnames(k8), ]
fm <- factorizeMatrix(k8)
allModDF <- data.frame(t(fm$proportions$cell), Sex = mdata$Gender, celdaCluster = paste0("K", celdaClusters(k8)), cellType = mdata$cellType, cellState = mdata$cellState, Status = mdata$Status, Sample = mdata$Sample_ID, rs1582763 = mdata$MS4, APOE4 = as.numeric(grepl("4", mdata$nAPOE)))
allModFilt <- allModDF
allModFilt$Status <- factor(allModFilt$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))
allModFilt$rs1582763 <- as.numeric(factor(allModFilt$rs1582763, levels = c("GG", "AG", "AA")))

# the following code is to run the sex*AD model for each module in all astrocytes
myHits <- list()
tmp <- lapply(seq_len(65), function(idx) {
  mod <- paste0("L", idx)
  re_ln2 <- lmer(paste0(mod, " ~ Sex + Status + rs1582763 + APOE4 + (1|Sample)"), data = allModFilt, REML = TRUE)
  z <- summary(re_ln2)
  myHits[[mod]] <<- z$coefficients[-1, ][z$coefficients[-1, "Pr(>|t|)"] < 0.05, , drop = F]
  return(z$coefficients)
})
qsave(tmp, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_gene_module_status_model.qs", nthreads = 8)
# myHits (here on box: /Box/Harari_Lab_Info/Projects/single nuclei RNAseq/07_Sex_differences_Logan/CeldaAnalyses/celdaGeneModules_ADstatus_APOE_rs1582763_associations.xlsx)
# $L1
#                     Estimate   Std. Error       df  t value   Pr(>|t|)
# StatusNeuro_ADAD 0.002414981 0.0012044372 58.01852 2.005070 0.04962845
# rs1582763        0.001080637 0.0004830011 58.05023 2.237338 0.02911799
#
# $L2
#                     Estimate  Std. Error       df  t value   Pr(>|t|)
# StatusNeuro_ADAD 0.002747009 0.001369181 58.03278 2.006314 0.04949059
#
# $L3
#               Estimate   Std. Error       df  t value  Pr(>|t|)
# rs1582763 0.0005825286 0.0002534147 57.67386 2.298717 0.0251642
#
# $L4
#               Estimate   Std. Error       df  t value   Pr(>|t|)
# rs1582763 0.0006212058 0.0002618688 57.28597 2.372202 0.02106347
#
# $L5
#                     Estimate   Std. Error      df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.004036462 0.0008172821 58.0592 4.938885 6.994291e-06
#
# $L6
#                     Estimate  Std. Error       df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.009477748 0.002677439 57.88061 3.539855 0.0007975667
#
# $L7
#                     Estimate   Std. Error       df  t value   Pr(>|t|)
# StatusNeuro_ADAD 0.002110126 0.0009517089 58.04708 2.217197 0.03053964
#
# $L8
#                     Estimate  Std. Error       df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.004017454 0.001065172 57.95677 3.771649 0.0003828802
#
# $L9
#                     Estimate  Std. Error       df  t value    Pr(>|t|)
# StatusNeuro_ADAD 0.003919498 0.001321039 57.94577 2.966981 0.004364512
#
# $L10
#                     Estimate   Std. Error       df  t value    Pr(>|t|)
# StatusNeuro_ADAD 0.002285929 0.0007316834 58.00257 3.124205 0.002782521
#
# $L11
#                     Estimate   Std. Error       df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.003597723 0.0008805144 58.00012 4.085933 0.0001365694
#
# $L12
#                     Estimate   Std. Error       df  t value    Pr(>|t|)
# StatusNeuro_ADAD 0.003552337 0.0013320080 57.53364 2.666904 0.009924095
# rs1582763        0.001280097 0.0005343019 57.62560 2.395830 0.019851565
#
# $L13
#                     Estimate   Std. Error       df  t value    Pr(>|t|)
# StatusNeuro_ADAD 0.004479381 0.0021312902 57.84543 2.101723 0.039943160
# rs1582763        0.002357347 0.0008547046 57.88249 2.758084 0.007767902
#
# $L14
#
# $L15
#             Estimate   Std. Error       df  t value    Pr(>|t|)
# rs1582763 0.00175168 0.0005888937 57.86529 2.974527 0.004274665
#
# $L16
#                      Estimate   Std. Error       df   t value    Pr(>|t|)
# StatusNeuro_ADAD -0.002028882 0.0006604658 57.73261 -3.071896 0.003242304
# APOE4             0.001098516 0.0004420075 58.01211  2.485288 0.015849303
#
# $L17
#                      Estimate  Std. Error       df   t value   Pr(>|t|)
# StatusNeuro_ADAD -0.002901022 0.001108239 57.62365 -2.617687 0.01128975
#
# $L18
#              Estimate   Std. Error       df  t value   Pr(>|t|)
# Sex2      0.001497783 0.0006315002 57.96016 2.371785 0.02104466
# rs1582763 0.001055528 0.0004291723 57.78062 2.459450 0.01692997
#
# $L19
#          Estimate   Std. Error       df  t value   Pr(>|t|)
# APOE4 0.001435028 0.0005535356 58.04061 2.592477 0.01203701
#
# $L20
#          Estimate   Std. Error       df  t value   Pr(>|t|)
# APOE4 0.001015989 0.0004804816 58.17397 2.114522 0.03876654
#
# $L21
#
# $L22
#
# $L23
#
# $L24
#                     Estimate  Std. Error       df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.004375047 0.001107645 57.46137 3.949865 0.0002161256
#
# $L25
#               Estimate   Std. Error       df   t value   Pr(>|t|)
# rs1582763 -0.001437921 0.0006201701 57.89871 -2.318591 0.02396915
#
# $L26
#                     Estimate  Std. Error       df  t value   Pr(>|t|)
# StatusNeuro_ADAD 0.005321161 0.002043811 57.56051 2.603548 0.01171671
#
# $L27
#                   Estimate   Std. Error       df t value   Pr(>|t|)
# StatusNeuro_ADAD 0.0025875 0.0009973597 57.43314 2.59435 0.01200625
#
# $L28
#
# $L29
#
# $L30
#                     Estimate   Std. Error       df  t value     Pr(>|t|)
# Sex2             0.001848538 0.0008080989 58.30901 2.287514 0.0258113142
# StatusNeuro_ADAD 0.005167104 0.0013690762 58.02108 3.774154 0.0003794951
#
# $L31
#         Estimate   Std. Error      df  t value    Pr(>|t|)
# Sex2 0.002887779 0.0009858036 58.0149 2.929366 0.004848665
#
# $L32
#         Estimate   Std. Error       df  t value   Pr(>|t|)
# Sex2 0.002018962 0.0008121625 57.89347 2.485909 0.01583055
#
# $L33
#
# $L34
#
# $L35
#                    Estimate  Std. Error       df  t value    Pr(>|t|)
# StatusNeuro_ADAD 0.00491163 0.001441504 57.93074 3.407296 0.001198878
#
# $L36
#                     Estimate  Std. Error       df  t value     Pr(>|t|)
# StatusNeuro_ADAD 0.004743761 0.001116501 58.08947 4.248773 7.875697e-05
#
# $L37
#
# $L38
#                      Estimate   Std. Error       df   t value   Pr(>|t|)
# Sex2             -0.002184764 0.0008884654 57.95607 -2.459031 0.01693836
# StatusNeuro_ADAD -0.003110179 0.0015064108 57.83935 -2.064628 0.04345178
# StatusNeuro_OT    0.003962294 0.0017137289 57.91375  2.312089 0.02434886
# rs1582763        -0.001384711 0.0006041758 57.90067 -2.291900 0.02556627
#
# $L39
#                      Estimate   Std. Error       df   t value   Pr(>|t|)
# Sex2             -0.002024638 0.0009955226 57.88056 -2.033744 0.04657007
# StatusNeuro_ADAD -0.004287808 0.0016871562 57.66376 -2.541441 0.01375175
#
# $L40
#          Estimate   Std. Error       df   t value   Pr(>|t|)
# Sex2 -0.001219234 0.0005154883 57.86515 -2.365202 0.02139365
#
# $L41
#                      Estimate  Std. Error       df   t value     Pr(>|t|)
# StatusNeuro_AD   -0.002454115 0.001029083 57.96526 -2.384758 2.038218e-02
# StatusNeuro_ADAD -0.005955610 0.001103158 57.89424 -5.398690 1.308718e-06
#
# $L42
#                      Estimate   Std. Error       df   t value    Pr(>|t|)
# Sex2              0.002885444 0.0008624767 58.13346  3.345533 0.001443221
# StatusNeuro_ADAD -0.004020337 0.0014617640 57.92854 -2.750333 0.007930234
#
# $L43
#                      Estimate  Std. Error       df   t value     Pr(>|t|)
# StatusNeuro_AD   -0.004387673 0.001916284 58.03681 -2.289678 2.569463e-02
# StatusNeuro_ADAD -0.010249783 0.002054149 57.95773 -4.989794 5.837470e-06
#
# $L44
#
# $L45
#                      Estimate Std. Error      df   t value     Pr(>|t|)
# StatusNeuro_ADAD -0.008501138 0.00217454 57.7865 -3.909397 0.0002455662
#
# $L46
#                     Estimate  Std. Error       df   t value    Pr(>|t|)
# StatusNeuro_ADAD -0.00671203 0.002376719 57.81087 -2.824075 0.006495226
#
# $L47
#                      Estimate  Std. Error       df   t value     Pr(>|t|)
# StatusNeuro_ADAD -0.006508943 0.001675783 57.90798 -3.884121 0.0002662225
#
# $L48
#                      Estimate  Std. Error       df   t value     Pr(>|t|)
# StatusNeuro_ADAD -0.006220911 0.001370959 57.83772 -4.537636 2.924862e-05
#
# $L49
#
# $L50
#                Estimate   Std. Error       df   t value   Pr(>|t|)
# rs1582763 -0.0008478234 0.0003898470 58.04588 -2.174759 0.03373623
# APOE4     -0.0015497131 0.0006506418 58.30447 -2.381822 0.02051061
#
# $L51
#
# $L52
#
# $L53
#
# $L54
#           Estimate  Std. Error       df   t value   Pr(>|t|)
# APOE4 -0.002964171 0.001200449 57.86465 -2.469218 0.01651412
#
# $L55
#           Estimate   Std. Error       df  t value   Pr(>|t|)
# APOE4 -0.001006071 0.0004719703 57.76562 -2.13164 0.03730196
#
# $L56
#           Estimate  Std. Error       df   t value Pr(>|t|)
# APOE4 -0.003080176 0.001182275 57.66017 -2.605296 0.011659
#
# $L57
#                      Estimate   Std. Error       df   t value    Pr(>|t|)
# StatusNeuro_ADAD -0.003589283 0.0013107948 57.68827 -2.738250 0.008201126
# APOE4            -0.001991433 0.0008779456 58.14257 -2.268288 0.027041425
#
# $L58
#                      Estimate   Std. Error       df   t value    Pr(>|t|)
# StatusNeuro_ADAD -0.002696412 0.0009941149 57.86705 -2.712375 0.008782488
#
# $L59
#
# $L60
#                     Estimate Std. Error       df t value    Pr(>|t|)
# StatusNeuro_ADAD 0.007454084 0.00243101 58.47491 3.06625 0.003279417
#
# $L61
#
# $L62
#
# $L63
#
# $L64
#                      Estimate   Std. Error       df   t value   Pr(>|t|)
# StatusNeuro_ADAD -0.004094553 0.0019744074 55.91800 -2.073814 0.04271401
# rs1582763         0.001656191 0.0007927741 56.21578  2.089109 0.04123669
#
# $L65

# the following code is to run the sex*AD model for each module in all astrocytes accounting for celda cluster
myHits <- list()
i <- 0
tmp <- lapply(seq_len(65), function(idx) {
  i <<- i + 1
  mod <- paste0("L", idx)
  re_ln2 <- lmer(paste0(mod, " ~ Sex + celdaCluster + Status + rs1582763 + APOE4 + (1|Sample)"), data = allModFilt, REML = TRUE)
  z <- summary(re_ln2)$coefficients
  z2 <- data.frame(z[!(rownames(z) %in% paste0("celdaClusterK", 1:8)), ])
  z2$mod <- mod
  z2 <- cbind(rownames(z2), z2)
  myHits[[mod]] <<- z2[-1, ][z2[-1, "Pr...t.."] < 0.05, , drop = F]
  return(z)
})
myHits2 <- do.call(rbind, myHits)
write.table(myHits2, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celdaGeneModules_ADstatus_APOE_rs1582763_associations.csv", sep = ",", quote = F)
qsave(tmp, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_gene_module_status_model_celdaCluster.qs", nthreads = 8)


# plot the L17 module score by Status using ggplot2
library(ggplot2)
p <- ggplot(allModFilt, aes(x = Status, y = L17)) +
  geom_jitter(width = 0.2, height = 0.01, alpha = 0.5) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("L17 module score by Status")
# save plot
ggsave(p, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celdaModule_L17_by_status.pdf", w = 7, h = 7)
```
```{r, run sex interaction models on the top genes for L17, L3, and L55}
#################################################################
# run sex interaction models on the top genes for L17
#################################################################
library(qs)
library(celda)

MOD_HITS <- c("L17", "L3", "L55")

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
L <- 65
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
fm <- factorizeMatrix(k8)

modListFull <- lapply(colnames(fm$posterior$module), function(mod) {
  return(fm$posterior$module[, mod])
})
modListFull <- lapply(modListFull, function(mod) {
  return(mod[order(mod, decreasing = T)])
})
names(modListFull) <- colnames(fm$posterior$module)
mod80Full <- lapply(modListFull, function(mod) { # using this filtering method: on average 23% of the genes for each module make up 80% of the overall signal
  ind <- 1
  while (sum(mod[1:ind]) < 0.8) ind <- ind + 1
  return(mod[1:ind])
})
names(mod80Full) <- colnames(fm$posterior$module)
genes <- unlist(lapply(MOD_HITS, function(mod) {
  return(names(mod80Full[[mod]]))
}))
rm(modListFull)
rm(mod80Full)

library(nebula)
library(Seurat)
library(qs)

pvalue.extreme <- function(z) {
  log.pvalue <- log(2) + pnorm(abs(z), lower.tail = FALSE, log.p = TRUE)
  log10.pvalue <- log.pvalue / log(10) ## from natural log to log10
  mantissa <- 10^(log10.pvalue %% 1)
  exponent <- log10.pvalue %/% 1
  ## or return(c(mantissa,exponent))
  # return(sprintf("p value is %1.2f times 10^(%d)",mantissa,exponent))
  return(sprintf("%1.2fE%d", mantissa, exponent))
}

# subclust1 = '6'#K6
date <- format(Sys.Date(), format = "%m.%d.%y")

m <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
m$celdaClusters <- celdaClusters(k8)
rm(k8)
m <- subset(m, subset = Sample_ID %in% names(table(m@meta.data$Sample_ID)[table(m@meta.data$Sample_ID) > 60])) # 60]))
m$Clusters <- Idents(m)
# m = subset(m,subset=celdaClusters == subclust1)
# m = subset(m,subset=Status %in% c('Neuro_CO','Neuro_AD'))#,'Neuro_ADAD') )

genes <- genes[genes %in% rownames(m)]

m$Sex <- as.factor(m$Gender)
m$AOD <- scale(as.numeric(m$AOD))
m$PMI <- scale(as.numeric(m$PMI))
m$Status <- factor(m$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))

pred <- model.matrix(~ Sex + Status + celdaClusters + Sex * Status, data = m@meta.data) # adding AOD dropped the lambda to 1.15 instead of 1.28
re_ln2 <- nebula(GetAssayData(m, slot = "counts")[genes, ], m@meta.data$Sample_ID, pred = pred, method = "LN", model = "NBLMM")
tmp2 <- data.frame("logFC_Sex.StatusNeuro_AD" = re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"])
tmp2$z.score <- re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"] / re_ln2$summary[, "se_Sex2:StatusNeuro_AD"]
tmp2$p.value <- pvalue.extreme(tmp2$z.score)
tmp2$BH <- p.adjust(re_ln2$summary[, "p_Sex2:StatusNeuro_AD"], "BH")
merged2 <- merge(tmp2, re_ln2$summary, by.x = "logFC_Sex.StatusNeuro_AD", by.y = "logFC_Sex2:StatusNeuro_AD")
rownames(merged2) <- merged2$gene
merged2 <- merged2[order(abs(merged2$z.score), decreasing = T), ]
write.table(t(merged2[seq(sum(merged2$BH < 0.05)), c(6, 7, 1, 25, 26, 3, 4)]), file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/sex_AD_interaction_genes.csv", sep = ",", quote = F, row.names = T, col.names = T)


# plot significant genes
library(ggplot2)
library(cowplot)

sigGenes <- rownames(merged2)[merged2$BH < 0.05]
df <- data.frame(t(GetAssayData(m, slot = "counts")[sigGenes, ]), Sex = as.character(m$Sex), Status = unlist(lapply(m$Status, function(x) strsplit(as.character(x), "_")[[1]][2])))
df$Status[df$Status == "AD"] <- "sAD"
df$Sex[df$Sex == 1] <- "Male"
df$Sex[df$Sex == 2] <- "Female"
df$Status_Sex <- paste(df$Status, df$Sex, sep = "-")
df$Status_Sex <- factor(df$Status_Sex, levels = c("CO-Female", "sAD-Female", "CO-Male", "sAD-Male"))
colnames(df)[which(colnames(df) == "FAM189A2")] <- sigGenes[which(sigGenes == "FAM189A2")] <- "ENTREP1"
plts <- lapply(sigGenes, function(gene) {
  p <- ggplot(na.omit(df), aes(x = Status_Sex, y = log(UQ(as.name(gene)) + 1), fill = Sex)) +
    geom_jitter(size = 0.5) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
    stat_summary(fun = "mean", geom = "crossbar", width = 0.75, color = "red") +
    ggtitle(gene) +
    theme_minimal() +
    xlab("Status-Sex") +
    theme(axis.text = element_text(color = "black"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  return(p)
})
q <- plot_grid(plotlist = plts, ncol = 2, nrow = ceiling(length(sigGenes) / 2))
ggsave(q, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/astro_sex_AD_interaction_gene_hits.pdf", w = 8, h = 4.5 * ceiling(length(sigGenes) / 2))

# L17 genes
# CD38       ARMH1      FAM189A2   MYLK       ITGB4      STUM       NAV1       LAMA2      GFAP       ZIC1       USP54      AL137145.2
# TTC21A     ANKRD28    CD99       AC110023.1 MASP1      CACNA2D3   PFKFB3     AC008127.1 ZNF135     PRKAG2     IGDCC4     KREMEN1
# CA5B       LIMK2      ANKFN1     PCED1B     MAML3      PKIA       PDK3       SNORC      LIX1       FRMPD2     LAMA1      CLTCL1
# SLC37A1    HMGCLL1    WDR11-AS1  AF165147.1 CEP78      OSBPL11    NDEL1      TMEM132B   ST6GALNAC3 KIAA1841   FBN1       PRKX
# GMPR       SPESP1     KIF6       MAMLD1     AC091078.1 PHYHD1     CCDC14

##################################################################
## run sex interaction models on the top genes for all nominally significant modules - NOT EVER RUN ##################################################################
# library(qs)
# sce = qread('~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs',nthreads = 8)
# L=65
# K=8
# k8 <- subsetCeldaList(sce, list(L = L, K = K))
# rm(sce)
#
# modListFull = lapply(colnames(fm$posterior$module),function(mod) return(fm$posterior$module[,mod]))
# modListFull = lapply(modListFull,function(mod) return(mod[order(mod,decreasing = T)]))
# names(modListFull) = colnames(fm$posterior$module)
# mod80Full = lapply(modListFull, function(mod) {#using this filtering method: on average 23% of the genes for each module make up 80% of the overall signal
#  ind = 1
#  while(sum(mod[1:ind]) < 0.8) ind = ind+1
#  return(mod[1:ind])
# })
# names(mod80Full) = colnames(fm$posterior$module)
# genes = names(mod80Full[['L17']])
# genes = unlist(lapply(names(mod80Full[['L17']])))
# rm(modListFull)
# rm(mod80Full)
#
# library(nebula)
# library(Seurat)
# library(qs)
#
# pvalue.extreme <- function(z) {
#  log.pvalue <- log(2) + pnorm(abs(z), lower.tail = FALSE, log.p = TRUE)
#  log10.pvalue <- log.pvalue/log(10) ## from natural log to log10
#  mantissa <- 10^(log10.pvalue %% 1)
#  exponent <- log10.pvalue %/% 1
#  ## or return(c(mantissa,exponent))
#  #return(sprintf("p value is %1.2f times 10^(%d)",mantissa,exponent))
#  return(sprintf("%1.2fE%d",mantissa,exponent))
# }
#
# subclust1 = '6'#K6
# date <- format(Sys.Date(),format='%m.%d.%y')
#
# m = readRDS('~/SingleCellProjects/dataObjects/astro.rds')
# m$celdaClusters = celdaClusters(k8)
# rm(k8)
# m = subset(m,subset=Sample_ID %in% names(table(m@meta.data$Sample_ID)[table(m@meta.data$Sample_ID) > 60])) #60]))
# m = subset(m,subset=celdaClusters == subclust1)
#
# m = subset(m,subset=Status %in% c('Neuro_CO','Neuro_AD','Neuro_ADAD') )
#
# genes = genes[genes %in% rownames(m)]
#
# m$Sex = as.factor(m$Gender)
# m$AOD = scale(as.numeric(m$AOD))
# m$PMI = scale(as.numeric(m$PMI))
# m$Status = factor(m$Status,levels=c('Neuro_CO','Neuro_AD','Neuro_ADAD'))
#
# pred = model.matrix(~Sex + Status + Sex*Status,data=m@meta.data) #adding AOD dropped the lambda to 1.15 instead of 1.28
# re_ln2 = nebula(GetAssayData(m,slot='counts')[genes,],m@meta.data$Sample_ID,pred=pred,method='LN',model='NBLMM')
# tmp2 = data.frame("logFC_Sex.StatusNeuro_AD" = re_ln2$summary[,'logFC_Sex2:StatusNeuro_AD'])
# tmp2$z.score = re_ln2$summary[,'logFC_Sex2:StatusNeuro_AD']/re_ln2$summary[,'se_Sex2:StatusNeuro_AD']
# tmp2$p.value = pvalue.extreme(tmp2$z.score)
# tmp2$BH      = p.adjust(re_ln2$summary[,'p_Sex2:StatusNeuro_AD'],'BH')
# merged2 = merge(tmp2,re_ln2$summary,by.x='logFC_Sex.StatusNeuro_AD',by.y='logFC_Sex2:StatusNeuro_AD')
# rownames(merged2) = merged2$gene
# merged2 = merged2[order(abs(merged2$z.score),decreasing=T),]
#
## plot significant genes
# library(ggplot2)
# library(cowplot)
#
# sigGenes = rownames(merged2)[merged2$BH < 0.05]
# df = data.frame(t(GetAssayData(m,slot='counts')[sigGenes,]),Sex = m$Sex, Status = m$Status)
# df$Status_Sex = paste(df$Status,df$Sex,sep='_')
# df$Status_Sex = factor(df$Status_Sex,levels=c('Neuro_CO_1','Neuro_AD_1','Neuro_ADAD_1','Neuro_CO_2','Neuro_AD_2','Neuro_ADAD_2'))
# plts = lapply(sigGenes,function(gene){
#  p = ggplot(df,aes(x=Status_Sex,y=log(UQ(as.name(gene))+1),fill=Sex)) + geom_jitter() + geom_violin(draw_quantiles = c(0.25,0.5,0.75),alpha=0.75) + stat_summary(fun='mean',geom = 'crossbar',width=0.75,color='red') + ggtitle(gene)
#  return(p)
# })
# q = plot_grid(plotlist= plts,ncol=3,nrow=1)
# ggsave(q,file='~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/astro_K6_L17_hits.pdf',w=21,h=7)
#
## L17 genes
## CD38       ARMH1      FAM189A2   MYLK       ITGB4      STUM       NAV1       LAMA2      GFAP       ZIC1       USP54      AL137145.2
## TTC21A     ANKRD28    CD99       AC110023.1 MASP1      CACNA2D3   PFKFB3     AC008127.1 ZNF135     PRKAG2     IGDCC4     KREMEN1
## CA5B       LIMK2      ANKFN1     PCED1B     MAML3      PKIA       PDK3       SNORC      LIX1       FRMPD2     LAMA1      CLTCL1
## SLC37A1    HMGCLL1    WDR11-AS1  AF165147.1 CEP78      OSBPL11    NDEL1      TMEM132B   ST6GALNAC3 KIAA1841   FBN1       PRKX
## GMPR       SPESP1     KIF6       MAMLD1     AC091078.1 PHYHD1     CCDC14
#################################################################
# see if there is a correlation between L17 and L3MBTL4 or TSHZ2 expression
#################################################################
# get data read for plotting
library(qs)
library(celda)
library(Seurat)
sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
L <- 65
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
fm <- factorizeMatrix(k8)
m <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
m$celdaClusters <- celdaClusters(k8)
rm(k8)

tmp <- as.matrix(GetAssayData(m, slot = "counts")[c("L3MBTL4", "TSHZ2"), ])

df <- data.frame(L3MBTL4 = tmp["L3MBTL4", ], TSHZ2 = tmp["TSHZ2", ], L17 = fm$proportions$cell["L17", ], Sex = as.character(m$Gender), Status = m$Status, CeldaClusters = m$celdaClusters, Sample = m$Sample_ID)
df$Sex[df$Sex == "1"] <- "Male"
df$Sex[df$Sex == "2"] <- "Female"
df$Status <- factor(df$Status, levels = c("Neuro_CO", unique(m$Status)[-3]))
qsave(df, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/df_plot_tf_L17.qs")
```
#################################################################
#plot
#################################################################
```{r,shift to console rather than terminal now that i don't need celda anymore}
# shift to console rather than terminal now that i don't need celda anymore
library(qs)
library(ggplot2)
library(lme4)
library(lmerTest)
df <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/df_plot_tf_L17.qs")

re_L3MBTL4 <- lmer(L17 ~ L3MBTL4 + Sex + Status + (1 | Sample), data = df, REML = T)
re_TSHZ2 <- lmer(L17 ~ TSHZ2 + Sex + Status + (1 | Sample), data = df, REML = T)

df$L17_corrected_L3MBTL4 <- (re_L3MBTL4@beta[2] * df$L3MBTL4) + resid(re_L3MBTL4)
df$L17_corrected_TSHZ2 <- (re_TSHZ2@beta[2] * df$TSHZ2) + resid(re_TSHZ2)

# ggplot(df, aes(x=L17_corrected_L3MBTL4, y=L3MBTL4, color=CeldaClusters) ) + geom_hex(aes(fill=stat(log(count)))) + scale_fill_continuous(type = "viridis") + theme_minimal() + geom_smooth(method='lm')
# ggplot(df, aes(x=L17_corrected_TSHZ2, y=TSHZ2, color=CeldaClusters) ) + geom_hex() + scale_fill_continuous(type = "viridis") + theme_minimal() + geom_smooth(method='lm')
```


```{r,shift to console rather than terminal now that i don't need celda anymore - plotting}
library(ggpubr)
summary(re_L3MBTL4)
summary(re_TSHZ2)
ggplot(df, aes(x = L17_corrected_L3MBTL4, y = L3MBTL4)) +
  geom_point() +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(method = "lm")
ggplot(df, aes(x = L17_corrected_TSHZ2, y = TSHZ2)) +
  geom_point() +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(method = "lm")

p <- ggplot(data = df) +
  geom_histogram(aes(x = L17_corrected_L3MBTL4, y = after_stat(count) / 300)) +
  geom_point(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4)) +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4), method = "lm")
p2 <- ggplot(data = df) +
  geom_histogram(aes(x = L17_corrected_TSHZ2, y = after_stat(count) / 200)) +
  geom_point(aes(x = L17_corrected_TSHZ2, y = TSHZ2)) +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(aes(x = L17_corrected_TSHZ2, y = TSHZ2), method = "lm")
q <- ggarrange(p, p2, ncol = 2, nrow = 1)
ggsave(q, filename = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/correlation_L17_TFs.pdf", width = 10, height = 5)
```

```{r, is there a certain celda cluster that has a greater association between the TFs and L17?}
library(qs)
library(ggplot2)
library(ggpubr)
options(expressions = 500000)

df <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/df_plot_tf_L17.qs")
myPlots <- list()
tmp <- lapply(seq_along(unique(df$CeldaClusters)), function(clust) {
  df2 <- df[df$CeldaClusters == clust, ]
  p <- ggplot(data = df2) +
    geom_histogram(aes(x = L17_corrected_L3MBTL4, y = after_stat(count))) +
    theme_minimal() +
    ylab("Histogram Counts") +
    ggtitle(sprintf("Celda Cluster: %s", clust))
  plotMax <- max(ggplot_build(p)$data[[1]]$count)
  p <- p +
    geom_point(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4 * plotMax / max(L3MBTL4))) +
    geom_smooth(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4 * plotMax / max(L3MBTL4)), method = "lm") +
    stat_cor(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4), method = "pearson") +
    scale_y_continuous(sec.axis = sec_axis(~ . / plotMax * max(df2$L3MBTL4), name = "L3MBTL4 Expression"))

  p2 <- ggplot(data = df2) +
    geom_histogram(aes(x = L17_corrected_TSHZ2, y = after_stat(count))) +
    theme_minimal() +
    ylab("Histogram Counts") +
    ggtitle(sprintf("Celda Cluster: %s", clust))
  plotMax <- max(ggplot_build(p2)$data[[1]]$count)
  p2 <- p2 +
    geom_point(aes(x = L17_corrected_TSHZ2, y = TSHZ2 * plotMax / max(TSHZ2))) +
    geom_smooth(aes(x = L17_corrected_TSHZ2, y = TSHZ2 * plotMax / max(TSHZ2)), method = "lm") +
    stat_cor(aes(x = L17_corrected_TSHZ2, y = TSHZ2), method = "pearson") +
    scale_y_continuous(sec.axis = sec_axis(~ . / plotMax * max(df2$TSHZ2), name = "TSHZ2 Expression"))
  myPlots[[length(myPlots) + 1]] <<- p
  myPlots[[length(myPlots) + 1]] <<- p2
  return(NULL)
})
q <- ggarrange(plotlist = myPlots, ncol = 2, nrow = length(unique(df$CeldaClusters)))
ggsave(q, filename = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/correlation_L17_TFs_byCeldaCluster.pdf", width = 10, height = 5 * length(unique(df$CeldaClusters)))
```

```{r, more investigation into the L17 signature and which cells express it}
library(qs)
library(celda)
library(Seurat)
library(ggplot2)

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
L <- 65
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
fm <- factorizeMatrix(k8)

a <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")

df <- data.frame(CellState = Idents(a), L17 = fm$proportions$cell[17, ], CeldaClusters = celdaClusters(k8))

table(df$CellState, df$CeldaClusters)
#       1    2    3    4    5    6    7    8
#  0  224 3092    3  256 9067  152 3071 5145
#  1 1660   10   20  316  470 6336  101 1115
#  2 1259 1557   34   18   14  238 2223    0
#  3   88   49    0 1195   88   34   60   64
#  4    3    0  688    0    0    0   27    0
p <- ggplot(data = df) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), aes(x = CellState, y = L17)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

hist(df$L17, breaks = 50)
outliers <- boxplot(df$L17)$out
df$outlier <- df$L17 %in% outliers
df$top10perc <- df$L17 > quantile(df$L17, 0.9)
table(df$outlier, df$CellState)
#            0     1     2     3     4
#  FALSE 20999  8728  5340  1574   718
#  TRUE     11  1300     3     4     0
table(df$outlier, df$CeldaClusters)
#           1    2    3    4    5    6    7    8
#  FALSE 3104 4708  744 1780 9636 5627 5481 6279
#  TRUE   130    0    1    5    3 1133    1   45
table(df$top10perc, df$CellState)
###            0     1     2     3     4
###  FALSE 20917  6287  5329  1560   716
###  TRUE     93  3741    14    18     2
table(df$top10perc, df$CeldaClusters)
#           1    2    3    4    5    6    7    8
#  FALSE 2725 4706  740 1761 9610 3738 5477 6052
#  TRUE   509    2    5   24   29 3022    5  272
```
#################################################################
#map the celda module scores onto a replication data set
#################################################################
```{r, figure out how to calculate the signature score}
library(qs)
library(celda)
sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
L <- 65
K <- 8
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)
fm <- factorizeMatrix(k8)
m <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
m$celdaClusters <- celdaClusters(k8)
rm(k8)

modListFull <- lapply(colnames(fm$posterior$module), function(mod) {
  return(fm$posterior$module[, mod])
})
modListFull <- lapply(modListFull, function(mod) {
  return(mod[order(mod, decreasing = T)])
})
names(modListFull) <- colnames(fm$posterior$module)

L17weights <- modListFull[["L17"]][modListFull[["L17"]] != 0]
l17genes <- names(modListFull[["L17"]][modListFull[["L17"]] != 0])
allgenes <- rownames(fm$proportions$module)
save(l17genes, allgenes, file = "~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/L17moduleGenes.Robj")

# l17_sub = fm$proportions$cell[17,1:5]
# this works!
myL17calc <- colSums(GetAssayData(m, slot = "counts")[l17genes, names(l17_sub)]) / colSums(GetAssayData(m, slot = "counts")[allgenes, names(l17_sub)])
```
```{r, map to rosmap data - run in console}
library(Seurat)
library(Matrix)
load("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/L17moduleGenes.Robj")
r <- readRDS("~/SingleCellProjects/dataObjects/Colonna_TREM2_data/colonna_seurat_object.rds")
# tmp = readRDS('~/SingleCellProjects/dataObjects/Colonna_TREM2_data/colonna_seurat_object_microglia.rds')
# tmp2 = unique(tmp@meta.data[,c('Sample','msex','age_death','rs1582763')])
# rownames(tmp2) = tmp2$Sample
# r$msex = unlist(lapply(r$Sample,function(x) return(tmp2[x,'msex'])))
# r$age_death = unlist(lapply(r$Sample,function(x) return(tmp2[x,'age_death'])))
# r$rs1582763 = unlist(lapply(r$Sample,function(x) return(tmp2[x,'rs1582763'])))
# saveRDS(r,'~/SingleCellProjects/dataObjects/Colonna_TREM2_data/colonna_seurat_object.rds')
r <- subset(r, subset = Label == "Astro")
allgenes <- allgenes[allgenes %in% rownames(r)] # 11706 out of 13302; none of the RNA genes are present
l17genes <- l17genes[l17genes %in% rownames(r)] # 137 out of 194; none of the RNA genes are present
# check the proportion of the module score this recovers
sum(L17weights[l17genes]) # 0.8801216;
summary(L17weights[!(names(L17weights)) %in% l17genes])
#     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
# 8.442e-05 4.241e-04 9.434e-04 2.103e-03 1.886e-03 1.487e-02

rL17 <- colSums(GetAssayData(r)[l17genes, ]) / colSums(GetAssayData(r)[allgenes, ])

tmp <- as.matrix(GetAssayData(r)[c("L3MBTL4", "TSHZ2", "FAM189A2", "CD38"), ])

df <- data.frame(L3MBTL4 = tmp["L3MBTL4", ], TSHZ2 = tmp["TSHZ2", ], CD38 = tmp["CD38", ], ENTREP1 = tmp["FAM189A2", ], L17 = rL17, Status = r$Status, Sample = r$Sample, Sex = as.character(r$msex))
rm(r)
df$Sex[df$Sex == "1"] <- "Male"
df$Sex[df$Sex == "0"] <- "Female"
df$Status <- factor(df$Status, levels = c("CO", "AD", "R62H"))
```
```{r,check for association between TFs and L17 score in the replication data}
# shift to console rather than terminal now that i don't need celda anymore
library(qs)
library(ggplot2)
library(lme4)
library(lmerTest)
# df = qread('~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/df_plot_tf_L17.qs')

re_L3MBTL4 <- lmer(L17 ~ L3MBTL4 + Sex + Status + (1 | Sample), data = df, REML = T)
re_TSHZ2 <- lmer(L17 ~ TSHZ2 + Sex + Status + (1 | Sample), data = df, REML = T)

df$L17_corrected_L3MBTL4 <- (re_L3MBTL4@beta[2] * df$L3MBTL4) + resid(re_L3MBTL4)
df$L17_corrected_TSHZ2 <- (re_TSHZ2@beta[2] * df$TSHZ2) + resid(re_TSHZ2)
```
```{r, check if L17 and the genes ENTREP1 and CD38 have a sex*AD interaction in the replication data}
# need to run the two above chunks first
library(lme4)
library(lmerTest)
library(nebula)

df2 <- df
df2$Status[df2$Status == "R62H"] <- "AD"
df2$Status <- factor(df2$Status, levels = c("CO", "AD"))
df2$Sex <- factor(df2$Sex, levels = c("Male", "Female"))

# test the L17 module score
re_ln2 <- lmer("L17 ~ Sex + Status + Sex*Status + (1|Sample)", data = df2, REML = TRUE) # nebula(m$DAM_up1,m@meta.data$Sample_ID,pred=pred,method='LN',model='gaussain')#'NBLMM')
#                    Estimate Std. Error        df t value Pr(>|t|)
# (Intercept)         0.011612   0.001270 28.384384   9.141 5.92e-10 ***
# SexFemale          -0.001306   0.001588 28.106624  -0.822   0.4178
# StatusAD           -0.003948   0.001500 28.193103  -2.631   0.0136 *
# SexFemale:StatusAD  0.001464   0.001935 28.047532   0.756   0.4558

# test the ENTREP1 and CD38 genes
pred <- model.matrix(~ Sex + Status + Sex * Status, data = df2)
re_ENTREP1 <- nebula(df2$ENTREP1, df2$Sample, pred = pred, method = "LN", model = "NBLMM")
#  logFC_(Intercept) logFC_SexFemale logFC_StatusAD logFC_SexFemale:StatusAD se_(Intercept)
#        -0.6459593       0.2629937     -0.4367354               -0.2782883     0.06195922
#  se_SexFemale se_StatusAD se_SexFemale:StatusAD p_(Intercept) p_SexFemale p_StatusAD
#    0.2186154    0.208416             0.2664577  1.895478e-25   0.2289774 0.03612674
#  p_SexFemale:StatusAD
#            0.2963005
re_CD38 <- nebula(df2$CD38, df2$Sample, pred = pred, method = "LN", model = "NBLMM")
# logFC_(Intercept) logFC_SexFemale logFC_StatusAD logFC_SexFemale:StatusAD se_(Intercept)
#         -1.962925       0.8285858    -0.09233009                -1.194039      0.1257298
#  se_SexFemale se_StatusAD se_SexFemale:StatusAD p_(Intercept) p_SexFemale p_StatusAD
#    0.4422261   0.4218167             0.5403168  6.008569e-55  0.06097593  0.8267383
#  p_SexFemale:StatusAD
#           0.02711305
```
```{r,shift to console rather than terminal now that i don't need celda anymore - plotting}
print(summary(re_L3MBTL4))
print(summary(re_TSHZ2))
ggplot(df, aes(x = L17_corrected_L3MBTL4, y = L3MBTL4)) +
  geom_point() +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(method = "lm")
ggplot(df, aes(x = L17_corrected_TSHZ2, y = TSHZ2)) +
  geom_point() +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(method = "lm")

ggplot(data = df) +
  geom_histogram(aes(x = L17_corrected_L3MBTL4, y = after_stat(count) / 800)) +
  geom_point(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4)) +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(aes(x = L17_corrected_L3MBTL4, y = L3MBTL4), method = "lm")
ggplot(data = df) +
  geom_histogram(aes(x = L17_corrected_TSHZ2, y = after_stat(count) / 300)) +
  geom_point(aes(x = L17_corrected_TSHZ2, y = TSHZ2)) +
  scale_fill_continuous(type = "viridis") +
  theme_minimal() +
  geom_smooth(aes(x = L17_corrected_TSHZ2, y = TSHZ2), method = "lm")
```
#################################################################
#check to see if L3MBTL4 and TSHZ2 are associated a sex*AD interaction
#################################################################
```{r, sex*AD interaction model for L3MBTL4 and TSHZ2}
library(qs)
library(nebula)
library(Seurat)

pvalue.extreme <- function(z) {
  log.pvalue <- log(2) + pnorm(abs(z), lower.tail = FALSE, log.p = TRUE)
  log10.pvalue <- log.pvalue / log(10) ## from natural log to log10
  mantissa <- 10^(log10.pvalue %% 1)
  exponent <- log10.pvalue %/% 1
  return(sprintf("%1.2fE%d", mantissa, exponent))
}

# subclust1 = '6'#K6
date <- format(Sys.Date(), format = "%m.%d.%y")

m <- readRDS("~/SingleCellProjects/dataObjects/astro.rds")
m <- subset(m, subset = Sample_ID %in% names(table(m@meta.data$Sample_ID)[table(m@meta.data$Sample_ID) > 60])) # 60]))

m$Sex <- as.factor(m$Gender)
m$AOD <- scale(as.numeric(m$AOD))
m$PMI <- scale(as.numeric(m$PMI))
m$Status <- factor(m$Status, levels = c("Neuro_CO", "Neuro_AD", "Neuro_ADAD", "Neuro_Presympt", "Neuro_OT"))

pred <- model.matrix(~ Sex + Status + Sex * Status, data = m@meta.data) # adding AOD dropped the lambda to 1.15 instead of 1.28
re_ln2 <- nebula(GetAssayData(m, slot = "counts")[c("L3MBTL4", "TSHZ2"), ], m@meta.data$Sample_ID, pred = pred, method = "LN", model = "NBLMM")
tmp2 <- data.frame("logFC_Sex.StatusNeuro_AD" = re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"])
tmp2$z.score <- re_ln2$summary[, "logFC_Sex2:StatusNeuro_AD"] / re_ln2$summary[, "se_Sex2:StatusNeuro_AD"]
tmp2$p.value <- pvalue.extreme(tmp2$z.score)
tmp2$BH <- p.adjust(re_ln2$summary[, "p_Sex2:StatusNeuro_AD"], "BH")
merged2 <- merge(tmp2, re_ln2$summary, by.x = "logFC_Sex.StatusNeuro_AD", by.y = "logFC_Sex2:StatusNeuro_AD")
rownames(merged2) <- merged2$gene
```
```{r, check to see if genes of interest are captured in the 13000 genes that pass selectFeaturs}
library(qs)
library(celda)

sce <- qread("~/SingleCellProjects/MyProjects/SexDifferences/celdaAnalyses/Astro/celda_astro_splitCell.qs", nthreads = 8)
K <- 8
L <- 65
k8 <- subsetCeldaList(sce, list(L = L, K = K))
rm(sce)

AD_genes_in_data <- read.table("/home/brasel/SingleCellProjects/MyProjects/67BrainsPaper/AD_GWAS_hits_plot/data/2022.08.19_GWAS_loci_genes_inData.csv", sep = ",", header = TRUE)
sum(AD_genes_in_data$Gene %in% rownames(k8)) # 499 of the 530 genes are in the data
AD_genes_in_data$Gene[!(AD_genes_in_data$Gene %in% rownames(k8))] # these are the genes that are not in the data
# [1] "AC004528.1" "ELANE"      "PRTN3"      "GPR139"
# [5] "AC090150.1" "PBK"        "PRSS53"     "PYDC1"
# [9] "SLC5A2"     "HLA-DQB2"   "TREM1"      "TREML4"
# [13] "OPN5"       "HDC"        "KLK15"      "KLK5"
# [17] "NKG7"       "SIGLEC5"    "AP001257.1" "MS4A6E"
# [21] "HSD17B2"    "DYDC2"      "LINC00857"  "TBCEL"
# [25] "OR9A2"      "PIP"        "TAS2R39"    "TAS2R40"
# [29] "CD244"      "LY9"        "SLAMF7"
```